# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3063f61c01ef5bd34d66ca5f60e1154c101626ee4734b8a12c826d855732caed7aaefc466199c34b8d208b7c7836c79bf042e12b1a91b1cf334f420adbe3f3c

test:
  secret_key_base: 373c0d2ac1f968220fbcf8c81020763ab0c8266415998e16c2ac8aca6ef3d83267c9fb8ed00bb44384546a44104dec2ef6aaee4b74e735517431d5aa0f34f56e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
